### ISSUE TITLE
Add documentation for quick start

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/not-a-build-harness#4]

**Comment by RothAndrew** [comment]
@andrewg-xyz would you mind adding a bit more context to this issue please so that we have a better idea of what you are thinking? We are looking for:

- What is being requested?
- Who is requesting it?
- Why is it needed?
- How do we know that we are done?

Happy to get together with you to get these things answered.

**Comment by andrewg-xyz** [comment]
Closing for now, I think this became OBE from my initial understanding during dash days
